packaged the Any23 server standalone with embedded jetty users will just have to download, unpack and run!
git-svn-id: https://svn.apache.org/repos/asf/incubator/any23/trunk@1231854 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/service/bin/any23server b/service/bin/any23server
--- a/service/bin/any23server
+++ b/service/bin/any23server
@@ -1,27 +1,90 @@
-#!/bin/bash
+#!/bin/sh
+# ----------------------------------------------------------------------------
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements. See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License.  You may obtain a copy of the License at
 
-###################################################################
-# This script runs the Any23 Service WAR using the Jetty container.
-#
-# External options can be passed via $ANY23_OPTS variable.
-###################################################################
+#  http://www.apache.org/licenses/LICENSE-2.0
 
-ANY23_ROOT=$(cd "$(dirname "$0")"; pwd -P)
-ANY23_ROOT="$ANY23_ROOT/.."
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+# ----------------------------------------------------------------------------
 
-if [ ! -e $ANY23_ROOT/target/any23-service-*.war ]; then
-    echo "Generating executable WAR..."
-    mvn -Dmaven.test.skip=true -o -f $ANY23_ROOT/pom.xml clean package\
-    	||
-    mvn -Dmaven.test.skip=true    -f $ANY23_ROOT/pom.xml clean package\
-        ||
-    { echo "Error while creating assembly"; exit 1; }
+BASEDIR=`dirname $0`/..
+BASEDIR=`(cd "$BASEDIR"; pwd)`
+
+# OS specific support.  $var _must_ be set to either true or false.
+cygwin=false;
+darwin=false;
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_VERSION" ] ; then
+             JAVA_VERSION="CurrentJDK"
+           else
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+           if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+           fi
+           ;;
+esac
+
+if [ -z "$JAVA_HOME" ] ; then
+  if [ -r /etc/gentoo-release ] ; then
+    JAVA_HOME=`java-config --jre-home`
+  fi
 fi
 
-echo Running Jetty...
-export MAVEN_OPTS="$ANY23_OPTS"
-{ mvn -o -f $ANY23_ROOT/pom.xml jetty:run; exit $?; }\
-    ||\
-  mvn    -f $ANY23_ROOT/pom.xml jetty:run \
-    ||\
-{ echo "Error while running Jetty."; exit 2; }
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+fi
+
+# If a specific java binary isn't specified search for the standard 'java' binary
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+      JAVACMD="$JAVA_HOME/bin/java"
+    fi
+  else
+    JAVACMD=`which java`
+  fi
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly."
+  echo "  We cannot execute $JAVACMD"
+  exit 1
+fi
+
+if [ -z "$REPO" ]
+then
+  REPO="$BASEDIR"/lib
+fi
+
+EXTRA_JVM_ARGUMENTS="-Xms500m -Xmx500m -XX:PermSize=128m -XX:-UseGCOverheadLimit"
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin; then
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
+  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
+  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
+fi
+
+exec "$JAVACMD" $JAVA_OPTS \
+  $EXTRA_JVM_ARGUMENTS \
+  -jar "$REPO"/jetty-runner-${jetty.runner.version}.jar \
+  --path /${project.artifactId} "$REPO"/${project.build.finalName}.${project.packaging}
