Improved commandline scripts.
git-svn-id: https://svn.apache.org/repos/asf/incubator/any23/trunk@1224132 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/any23-core/bin/any23tools b/any23-core/bin/any23tools
--- a/any23-core/bin/any23tools
+++ b/any23-core/bin/any23tools
@@ -1,10 +1,21 @@
 #!/bin/bash
+
+###################################################################
+# This script runs the Any23 ToolRunner commandline utility.
+#
+# External options can be passed via $ANY23_OPTS variable.
+###################################################################
+
 ANY23_ROOT=$(cd "$(dirname "$0")"; pwd -P)
 ANY23_ROOT="$ANY23_ROOT/.."
 
 if [ ! -e $ANY23_ROOT/target/*-jar-with-dependencies.jar ]; then 
     echo "Generating executable JAR..."
-    mvn -f $ANY23_ROOT/pom.xml -Dmaven.test.skip=true clean assembly:assembly	
+    mvn -o -f $ANY23_ROOT/pom.xml -Dmaven.test.skip=true clean assembly:assembly\
+        ||\
+    mvn    -f $ANY23_ROOT/pom.xml -Dmaven.test.skip=true clean assembly:assembly\
+    	||\
+    { echo "Error while generating commandline assembly."; exit 1; }
 fi
 
 SEP=':'
@@ -14,4 +25,4 @@ do
   if [ ! -e "$jar" ]; then continue; fi
   CP="$CP$SEP$jar"
 done
-exec java -cp "$CP" -Xmx256M org.deri.any23.cli.ToolRunner ../target/*-jar-with-dependencies.jar "$@"
+exec java $ANY23_OPTS -cp "$CP" -Xmx256M org.deri.any23.cli.ToolRunner ../target/*-jar-with-dependencies.jar "$@"
